# Generated by Django 6.0.5 on 2026-05-21 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_alter_organization_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('event_name', models.CharField(blank=True, max_length=255)),
                ('metric', models.CharField(default='count', max_length=50)),
                ('operator', models.CharField(choices=[('gt', '>'), ('gte', '>='), ('lt', '<'), ('lte', '<='), ('eq', '=')], default='gt', max_length=10)),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=12)),
                ('time_window_minutes', models.PositiveIntegerField(default=10)),
                ('enable_in_app', models.BooleanField(default=True)),
                ('enable_email', models.BooleanField(default=False)),
                ('email_to', models.EmailField(blank=True, max_length=254)),
                ('enable_webhook', models.BooleanField(default=False)),
                ('webhook_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('triggered', 'Triggered'), ('resolved', 'Resolved'), ('muted', 'Muted')], default='active', max_length=20)),
                ('muted_until', models.DateTimeField(blank=True, null=True)),
                ('last_triggered_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('last_evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_alert_rules', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='organizations.organization')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('triggered', 'Triggered'), ('resolved', 'Resolved'), ('muted', 'Muted'), ('evaluated', 'Evaluated')], max_length=30)),
                ('triggered_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_history', to='organizations.organization')),
                ('alert_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='alerts.alertrule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('in_app', 'In App'), ('email', 'Email'), ('webhook', 'Webhook')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('alert_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='alerts.alertrule')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['organization', 'status'], name='alerts_aler_organiz_6aba83_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['organization', 'event_name'], name='alerts_aler_organiz_8f2965_idx'),
        ),
    ]
